# -*- coding: utf-8 -*-
"""RegressionTask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gL7v_KAlR1itOciXZCbN5TcLTYKJ2m18

# Regression Task: Beijing PM2.5 Prediction

**Dataset:** Beijing PM2.5 Data  
**Source:** UCI Machine Learning Repository  
**Target Variable:** `pm2.5`, renamed as `pm25` in the notebook  
**Task Type:** Regression

## Task 1: Exploratory Data Analysis and Data Understanding

## Task 1.1: Choosing a Dataset

For this regression task, I selected the **Beijing PM2.5 Data** dataset from the **UCI Machine Learning Repository**.

The dataset was created by **Song Chen** and donated to the UCI Machine Learning Repository on **18 January 2017**. The related research paper was published in 2015. The dataset contains hourly data from **1 January 2010 to 31 December 2014**.

I accessed the dataset from the UCI Machine Learning Repository:
https://archive.ics.uci.edu/dataset/381/beijing+pm2+5+data

The dataset contains PM2.5 air pollution measurements from the **US Embassy in Beijing** and weather data from **Beijing Capital International Airport**.

### UNSDG Alignment

This dataset mainly aligns with **UNSDG 3: Good Health and Well-being**, because PM2.5 pollution can affect human health, especially respiratory and cardiovascular health.

It also relates to **UNSDG 11: Sustainable Cities and Communities**, because monitoring and understanding air pollution supports cleaner and safer urban environments.

### Attribute Description

| Column | Description |
|---|---|
| No | Row number or record ID |
| year | Year of observation |
| month | Month of observation |
| day | Day of observation |
| hour | Hour of observation |
| pm2.5 | PM2.5 concentration in micrograms per cubic meter; target variable |
| DEWP | Dew point temperature in degrees Celsius |
| TEMP | Temperature in degrees Celsius |
| PRES | Atmospheric pressure in hPa |
| cbwd | Combined wind direction |
| Iws | Cumulated wind speed in m/s |
| Is | Cumulated hours of snow |
| Ir | Cumulated hours of rain |

### Potential Questions

1. Can PM2.5 concentration be predicted using weather and time-related variables?
2. Which weather variables are most related to PM2.5 concentration?
3. How does PM2.5 concentration change by year, month, hour, and wind direction?

### Dataset Suitability

The dataset is suitable for regression because the target variable, PM2.5 concentration, is continuous numerical data. It also has a large number of hourly records, which is useful for training and testing machine learning models.

However, the dataset is not perfect. The PM2.5 column has missing values, so cleaning is required. The dataset also contains extreme PM2.5 values, which need to be checked because they may affect model performance. Overall, the dataset is relevant, large enough, and appropriate for predicting air pollution levels.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.feature_selection import RFE

from google.colab import files
uploaded = files.upload()

file_name = "PRSA_data_2010.1.1-2014.12.31.csv"

df = pd.read_csv(file_name)
df.head()

"""#Exploratory Data Analysis (EDA):

Initial Data Inspection
"""

df.head()

df.shape

df.columns

df.dtypes

df.info()

df = df.rename(columns= {"pm2.5" : "pm25"})
df.columns

"""I first inspect the shape, columns, data types, and a few rows. This confirms that the CSV has loaded correctly and helps identify basic cleaning steps before modelling.

#Data Cleaning
"""

df.isnull().sum()

missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

"""Only pm25 has missing values. Since pm25 is the target variable, these rows cannot be used for supervised learning because the model would not know the correct answer during training or evaluation. I remove rows where the target is missing."""

df_clean = df.dropna(subset=["pm25"]).copy()
print(df_clean.isnull().sum())

duplicate_count = df_clean.duplicated().sum()
print("number of duplicate rows :", duplicate_count)

# Removing duplicate rows if there are any

df_clean = df_clean.drop_duplicates()
print("Shape after cleaning:", df_clean.shape)

df_clean["datetime"] = pd.to_datetime(df_clean[["year","month", "day" , "hour"]])
df_clean.head()

#creating season variable from month
df_clean["season"] = "winter"
df_clean.loc[(df_clean["month"] >= 3) & (df_clean["month"] <= 6), "season"] = "spring"
df_clean.loc[(df_clean["month"] >= 6) & (df_clean["month"] <= 8), "season"] = "Summer"
df_clean.loc[(df_clean["month"] >= 9) & (df_clean["month"] <= 11), "season"] = "Autumn"

df_clean.head()

print("Start date:", df_clean["datetime"].min())
print("End date:", df_clean["datetime"].max())
print("Wind direction values:", df_clean["cbwd"].unique())
print("Season values:", df_clean["season"].unique())

df_clean.describe()

"""The summary statistics provide the mean, median, standard deviation, minimum, maximum, and quartiles for the numerical variables. These values are useful for understanding scale, spread, and possible extreme observations before choosing models and preprocessing steps."""

Q1 = df_clean["pm25"].quantile(0.25)
Q3 = df_clean["pm25"].quantile(0.75)
iqr = Q3 - Q1
lower_bound = Q1 - 1.5 * iqr
upper_bound = Q3 + 1.5 * iqr

outliers = df_clean[(df_clean["pm25"]<lower_bound) | (df_clean["pm25"]>upper_bound)]
print("lower bound:",lower_bound)
print("upper bound:",upper_bound)
print("number of pm25 outliers is :",outliers.shape[0])

"""#Visualization

##1:Distribution of PM2.5
"""

plt.figure(figsize=(8, 6))
sns.histplot(df_clean["pm25"], bins=30, kde=True)
plt.title("Distribution of PM2.5 Cocentration")
plt.xlabel("PM2.5")
plt.ylabel("Frequency")
plt.show()

"""The histogram shows that the PM2.5 data is positively right-skewed. Most of the PM2.5 values are low to moderate, while only a few values are very high. This creates a long tail on the right side, which means high pollution levels are less common.

##2: Boxplot of PM2.5
"""

plt.figure(figsize=(8,4))
sns.boxplot(x=df_clean["pm25"])
plt.title("Boxplot of PM2.5 Concentration")
plt.xlabel("PM2.5")
plt.show()

"""The boxplot confirms that PM2.5 has high outlier values. These values shows serious pollution events.

#3: Correlation Heatmap
"""

plt.figure(figsize=(10,7))
corr_matrix = df_clean.corr(numeric_only=True)
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

print(corr_matrix["pm25"].sort_values(ascending=False))

"""The heatmap shows the correlation between the numerical variables in the dataset. It helps identify which features have positive, negative, or weak relationships with PM2.5, making it useful for understanding the data before building prediction models.

### 4: PM2.5 vs Temperature
"""

plt.figure(figsize=(10, 6))
sns.scatterplot(x="TEMP", y="pm25", data=df_clean , alpha=0.4)
plt.title("PM2.5 vs Temperature")
plt.xlabel("Temperature")
plt.ylabel("PM2.5")

"""The scatter plot shows the relationship between Temperature and PM2.5 concentration. The points are widely scattered without a clear upward or downward trend, indicating a weak relationship between the two variables. Most observations have PM2.5 values below 400, while a few very high values appear as potential outliers.

##5: PM2.5 vs Wind Speed
"""

plt.figure(figsize=(10, 6))
sns.scatterplot(x="Iws", y="pm25", data=df_clean , alpha=0.4)
plt.title("PM2.5 vs Cumulated Wind Speed")
plt.xlabel("Wind Speed (Iws)")
plt.show()

"""The scatter plot indicates a negative relationship between cumulated wind speed and PM2.5. Most high PM2.5 values occur at low wind speeds, while PM2.5 generally decreases as wind speed increases. A few outliers are also present.

##6: Average PM2.5 by Year
"""

yearly_pm_25 = df_clean.groupby("year")["pm25"].mean()
plt.figure(figsize=(10, 6))
yearly_pm_25.plot(kind="bar")
plt.title("Average PM2.5 by Year")
plt.xlabel("Year")
plt.ylabel("Average PM2.5")
plt.show()

"""The bar chart shows the average PM2.5 concentration for each year from 2010 to 2014. The average PM2.5 was highest in 2010, decreased to its lowest level in 2012, increased again in 2013, and slightly decreased in 2014. Overall, the average PM2.5 varied across the years without showing a consistent increasing or decreasing trend.

##7: Average PM2.5 by Month
"""

monthly_pm_25 = df_clean.groupby("month")["pm25"].mean()
plt.figure(figsize=(8, 5))
monthly_pm_25.plot(kind="line" , marker="o")
plt.title("Average PM2.5 by Month")
plt.xlabel("Month")
plt.ylabel("Average PM2.5")
plt.show()

"""The line chart shows average PM2.5 concentration for each month. The average PM2.5 is highest in February and October, while May and August have the lowest averages. Overall, PM2.5 levels fluctuate throughout the year without following a consistent increasing or decreasing trend.

##8: Average PM2.5 by Hour
"""

hourly_pm25 = df_clean.groupby("hour")["pm25"].mean()
plt.figure(figsize=(8, 5))
hourly_pm25.plot(kind="line", marker ="o")
plt.title("Average PM2.5 by Hour")
plt.xlabel("Hour")
plt.ylabel("Average PM2.5")
plt.show()

"""The line chart shows that the average PM2.5 level changes throughout the day. It is highest during the early morning and late evening, while the lowest average occurs in the afternoon.It shows pm2.5 of evry hour and it fluctuates and does not stay same.

## 9: Average PM2.5 by Wind Direction
"""

plt.figure(figsize=(8, 5))
sns.barplot(x="cbwd", y="pm25", data=df_clean)
plt.title("Average PM2.5 by Wind Direction")
plt.xlabel("Wind Direction")
plt.ylabel("Average PM2.5")
plt.show()

"""The bar chart shows that the average PM2.5 concentration varies by wind direction. The CV wind direction has the highest average PM2.5, while NW has the lowest.

#EDA Summary:

The dataset contains hourly air pollution and weather data. Missing target values were removed, and duplicate records were checked. PM2.5 has a right-skewed distribution with high outlier values, which were retained because they represent real pollution events. The analysis showed that PM2.5 varies across years, months, hours, and wind directions. Correlation analysis and scatter plots also indicated that several weather variables have relationships with PM2.5, suggesting that time and weather features may be useful for predicting PM2.5 concentration.

#Data Preparation for Machine Learning

Since machine learning models require numerical input, I prepared the dataset before training the neural network. I removed columns that were not useful for prediction, separated the target variable from the input features, converted categorical variables into dummy variables, split the data into training and testing sets, and scaled the features using StandardScaler.
"""

#making copy of clean dataset for modelling
model_data = df_clean.copy()
#dropping columns that are not useful for prediction
model_data = model_data.drop(columns=["No","datetime"])
#converting categorical column into numerical dummy variables
model_data = pd.get_dummies(model_data, columns = ["cbwd" , "season"], drop_first=True , dtype=int)

model_data.head()

# Separating input features and target variable

X = model_data.drop("pm25", axis=1)
y = model_data["pm25"]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

X.head()

# Spliting dataset into training and testing set 80 percent dat for lrearning or testing and 20 percent for test or predicting

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training feature shape:", X_train.shape)
print("Testing feature shape:", X_test.shape)

# Scaling  features for Linear Regression and Neural Network

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""The dataset was divided into 80% training data and 20% testing data. Then, StandardScaler was used to make the numerical features have a similar scale. The scaler learned the scaling information from the training data only and used the same information to scale the testing data. This helps many machine learning models, especially neural networks and linear models, learn more effectively and avoids data leakage.

#Task 2 Build a Neural Network Model for Regression

I used `MLPRegressor` from scikit-learn to build a neural network regression model.

The network architecture is:

- Input layer: 16 input features
- Hidden layer 1: 64 neurons
- Hidden layer 2: 32 neurons
- Activation function: ReLU
- Output layer: 1 continuous output value for predicted PM2.5
- Optimizer: Adam
- Loss function: Squared error loss

I also used `early_stopping=True`, which stops training when the model stops improving. This helps reduce overfitting. This model is suitable because PM2.5 prediction is a regression problem, and neural networks can learn nonlinear relationships between weather, time, and pollution variables.

# Training Neural Network Model
"""

mlp_model = MLPRegressor(
    hidden_layer_sizes=(64, 32),
    activation="relu",
    solver="adam",
    max_iter=500,
    early_stopping=True,
    random_state=42
)

mlp_model.fit(X_train_scaled, y_train)

"""#Evaluating Neural Network Model"""

mlp_train_predictions = mlp_model.predict(X_train_scaled)
mlp_test_predictions = mlp_model.predict(X_test_scaled)

print("Training MSE:", mean_squared_error(y_train, mlp_train_predictions))
print("Training RMSE:", np.sqrt(mean_squared_error(y_train, mlp_train_predictions)))
print("Training R2:", r2_score(y_train, mlp_train_predictions))

print("Testing MSE:", mean_squared_error(y_test, mlp_test_predictions))
print("Testing RMSE:", np.sqrt(mean_squared_error(y_test, mlp_test_predictions)))
print("Testing R2:", r2_score(y_test, mlp_test_predictions))

"""The neural network achieved a training R² of **0.705** and a testing R² of **0.672**. This means the model explains about 70.5% of the variation in the training data and about 67.2% of the variation in the testing data.

The testing RMSE is **53.74**, meaning the model predictions are typically about 54 PM2.5 units away from the actual values. The training and testing results are reasonably close, so the model does not show serious overfitting. However, the testing error is still quite high, which may be due to extreme PM2.5 pollution values and nonlinear patterns in the dataset.

## Task 3: Build Primary Machine Learning Models

For the classical machine learning models, I used:

1. Linear Regression
2. Random Forest Regressor

Linear Regression was used as a simple baseline model. Random Forest Regressor was used because it can capture nonlinear relationships between the input features and PM2.5 concentration.

For Linear Regression, I used the scaled training and testing data. For Random Forest, I used the original unscaled data because tree-based models do not require feature scaling.
"""

def evaluate_model(model, X_test, y_test):
    predictions = model.predict(X_test)

    mse = mean_squared_error(y_test, predictions)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test, predictions)
    r2 = r2_score(y_test, predictions)

    return mse, rmse, mae, r2

"""Model - 1 Linear Regression"""

linear_model = LinearRegression()
linear_model.fit(X_train_scaled, y_train)

linear_mse, linear_rmse, linear_mae, linear_r2 = evaluate_model(
    linear_model, X_test_scaled, y_test
)

print("Linear Regression MSE:", linear_mse)
print("Linear Regression RMSE:", linear_rmse)
print("Linear Regression MAE:", linear_mae)
print("Linear Regression R2:", linear_r2)

"""Model 2 - Random Forest Regressor"""

random_forest_model = RandomForestRegressor(
    n_estimators=50,
    random_state=42
)

random_forest_model.fit(X_train, y_train)

rf_mse, rf_rmse, rf_mae, rf_r2 = evaluate_model(
    random_forest_model, X_test, y_test
)

print("Random Forest MSE:", rf_mse)
print("Random Forest RMSE:", rf_rmse)
print("Random Forest MAE:", rf_mae)
print("Random Forest R2:", rf_r2)

"""Initial Model Comparison"""

initial_results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest Regressor"],
    "MSE": [linear_mse, rf_mse],
    "RMSE": [linear_rmse, rf_rmse],
    "MAE": [linear_mae, rf_mae],
    "R2 Score": [linear_r2, rf_r2]
})

initial_results.round(3)

"""The Random Forest Regressor performed much better than Linear Regression. It achieved a lower MSE, RMSE, and MAE, and a much higher R² score.

Linear Regression achieved an R² score of **0.308**, meaning it explained only about 30.8% of the variation in PM2.5 values. Random Forest achieved an R² score of **0.821**, meaning it explained about 82.1% of the variation in the test data.

Random Forest also had a much lower RMSE of **39.77**, compared with **78.08** for Linear Regression. This suggests that Random Forest is better for this dataset because the relationship between weather, time variables, and PM2.5 is likely nonlinear.

## Task 4: Hyperparameter Optimization with Cross-Validation

I used GridSearchCV to tune the hyperparameters of the two classical machine learning models from Task 3.

For Linear Regression, I tested:

- `fit_intercept`: whether the model should calculate an intercept value.

For Random Forest Regressor, I tested:

- `n_estimators`: the number of trees in the forest.
- `max_depth`: the maximum depth of each tree.
- `min_samples_split`: the minimum number of samples required to split a node.
- `min_samples_leaf`: the minimum number of samples required at a leaf node.

GridSearchCV tests different combinations of hyperparameter values and uses cross-validation to estimate model performance. I used R² as the scoring metric because this is a regression problem and R² shows how much variation in PM2.5 is explained by the model.

GridSearchCV for Linear Regression
"""

linear_parameters = {
    "fit_intercept": [True, False]
}

linear_grid = GridSearchCV(
    LinearRegression(),
    linear_parameters,
    cv=5,
    scoring="r2"
)

linear_grid.fit(X_train_scaled, y_train)

print("Best Linear Regression Parameters:", linear_grid.best_params_)
print("Best Linear Regression CV Score:", linear_grid.best_score_)

"""GridSearchCV for Random Forest Regressor"""

rf_parameters = {
    "n_estimators": [50, 100],
    "max_depth": [10, 20, None],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}
rf_grid = GridSearchCV(
    RandomForestRegressor(random_state=42),
    rf_parameters,
    cv=3,
    scoring="r2",
    n_jobs=-1
)

rf_grid.fit(X_train, y_train)

print("Best Random Forest Parameters:", rf_grid.best_params_)
print("Best Random Forest CV Score:", rf_grid.best_score_)

tuning_results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest Regressor"],
    "Best Parameters": [linear_grid.best_params_, rf_grid.best_params_],
    "Best CV R2 Score": [linear_grid.best_score_, rf_grid.best_score_]
})

tuning_results
tuning_results.round(3)

"""The best Linear Regression parameter was `fit_intercept=True`, with a cross-validation R² score of **0.314**. This shows that Linear Regression has limited predictive performance on this dataset.

The best Random Forest parameters were `max_depth=None`, `min_samples_leaf=1`, `min_samples_split=2`, and `n_estimators=100`, with a cross-validation R² score of **0.797**. This is much higher than the Linear Regression CV score.

Therefore, Random Forest performs better after cross-validation and is more suitable for this dataset. This is likely because Random Forest can capture nonlinear relationships between weather, time variables, and PM2.5 concentration.

## Feature Selection

I used Recursive Feature Elimination (RFE) for feature selection. RFE is a wrapper-based feature selection method. It works by training a model, ranking the features, removing the weakest features, and repeating this process until the required number of features remains.

I used RFE separately for Linear Regression and Random Forest because different models may find different features useful. Linear Regression selects features based on linear relationships, while Random Forest can capture nonlinear relationships and interactions between features.

I selected the top 10 features to reduce the number of input variables while still keeping enough information for prediction. This can make the final models simpler and easier to interpret.

RFE for Linear Regression
"""

# Feature selection for Linear Regression using RFE

linear_rfe = RFE(
    estimator=LinearRegression(),
    n_features_to_select=10
)

linear_rfe.fit(X_train_scaled, y_train)

linear_selected_features = X_train.columns[linear_rfe.support_]

print("Selected features for Linear Regression:")
print(linear_selected_features)

linear_feature_ranking = pd.DataFrame({
    "Feature": X_train.columns,
    "Selected": linear_rfe.support_,
    "Ranking": linear_rfe.ranking_
})

linear_feature_ranking.sort_values("Ranking")

"""RFE for Random Forest"""

# Feature selection for Random Forest using RFE

rf_rfe = RFE(
    estimator=RandomForestRegressor(n_estimators=50, random_state=42),
    n_features_to_select=10
)

rf_rfe.fit(X_train, y_train)

rf_selected_features = X_train.columns[rf_rfe.support_]

print("Selected features for Random Forest:")
print(rf_selected_features)

rf_feature_ranking = pd.DataFrame({
    "Feature": X_train.columns,
    "Selected": rf_rfe.support_,
    "Ranking": rf_rfe.ranking_
})

rf_feature_ranking.sort_values("Ranking")

# Selected data for Linear Regression

X_train_linear_selected = X_train[linear_selected_features]
X_test_linear_selected = X_test[linear_selected_features]

# Selected data for Random Forest

X_train_rf_selected = X_train[rf_selected_features]
X_test_rf_selected = X_test[rf_selected_features]

# Scale selected features for Linear Regression

linear_selected_scaler = StandardScaler()

X_train_linear_selected_scaled = linear_selected_scaler.fit_transform(X_train_linear_selected)
X_test_linear_selected_scaled = linear_selected_scaler.transform(X_test_linear_selected)

print("Linear Regression selected training shape:", X_train_linear_selected.shape)
print("Linear Regression selected testing shape:", X_test_linear_selected.shape)

print("Random Forest selected training shape:", X_train_rf_selected.shape)
print("Random Forest selected testing shape:", X_test_rf_selected.shape)

"""RFE selected 10 features for each model. For Linear Regression, the selected features include weather variables such as `DEWP`, `TEMP`, `PRES`, `Iws`, and `Ir`, as well as time and categorical dummy variables. These features are useful because PM2.5 concentration can be affected by weather conditions, wind direction, and seasonal patterns.

For Random Forest, RFE selected time variables such as `year`, `month`, `day`, and `hour`, along with weather variables such as `DEWP`, `TEMP`, `PRES`, and `Iws`. This suggests that Random Forest uses both time-based patterns and weather-related variables to predict PM2.5.

The selected features are not exactly the same for both models because Linear Regression and Random Forest learn relationships differently. These selected feature sets will be used in the final model building step.

#Task 6: Final Models and Comparative Analysis

Final Linear Regression Model
"""

# Final Linear Regression model using best hyperparameter and selected features
final_linear_model = LinearRegression(
    fit_intercept=linear_grid.best_params_["fit_intercept"]
)

final_linear_model.fit(X_train_linear_selected_scaled, y_train)

final_linear_mse, final_linear_rmse, final_linear_mae, final_linear_r2 = evaluate_model(
    final_linear_model,
    X_test_linear_selected_scaled,
    y_test
)

print("Final Linear Regression MSE:", final_linear_mse)
print("Final Linear Regression RMSE:", final_linear_rmse)
print("Final Linear Regression MAE:", final_linear_mae)
print("Final Linear Regression R2:", final_linear_r2)

"""Final Random Forest Model"""

final_rf_model = RandomForestRegressor(
    n_estimators=rf_grid.best_params_["n_estimators"],
    max_depth=rf_grid.best_params_["max_depth"],
    min_samples_split=rf_grid.best_params_["min_samples_split"],
    min_samples_leaf=rf_grid.best_params_["min_samples_leaf"],
    random_state=42
)

final_rf_model.fit(X_train_rf_selected, y_train)

final_rf_mse, final_rf_rmse, final_rf_mae, final_rf_r2 = evaluate_model(
    final_rf_model,
    X_test_rf_selected,
    y_test
)

print("Final Random Forest MSE:", final_rf_mse)
print("Final Random Forest RMSE:", final_rf_rmse)
print("Final Random Forest MAE:", final_rf_mae)
print("Final Random Forest R2:", final_rf_r2)

"""Cross-Validation Scores"""

# Cross-validation score for final Linear Regression

final_linear_cv_scores = cross_val_score(
    final_linear_model,
    X_train_linear_selected_scaled,
    y_train,
    cv=5,
    scoring="r2"
)

final_linear_cv_score = final_linear_cv_scores.mean()


# Cross-validation score for final Random Forest

final_rf_cv_scores = cross_val_score(
    final_rf_model,
    X_train_rf_selected,
    y_train,
    cv=3,
    scoring="r2"
)

final_rf_cv_score = final_rf_cv_scores.mean()

print("Final Linear Regression CV Score:", final_linear_cv_score)
print("Final Random Forest CV Score:", final_rf_cv_score)

"""Final Comparison Table"""

# Final comparison table

final_results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest Regressor"],
    "Features Used": [len(linear_selected_features), len(rf_selected_features)],
    "CV Score": [final_linear_cv_score, final_rf_cv_score],
    "Test RMSE": [final_linear_rmse, final_rf_rmse],
    "Test R-squared": [final_linear_r2, final_rf_r2],
    "Test MSE": [final_linear_mse, final_rf_mse],
    "Test MAE": [final_linear_mae, final_rf_mae]
})

final_results.round(3)

"""The final Random Forest Regressor performed better than the final Linear Regression model. It achieved a much lower test RMSE of **39.01**, compared with **78.53** for Linear Regression. It also achieved a higher test R² score of **0.827**, compared with **0.300** for Linear Regression.

The Random Forest model also had a higher cross-validation score of **0.795**, while Linear Regression had a CV score of **0.307**. This shows that Random Forest performed better not only on the test set but also during cross-validation.

Compared with the initial Random Forest model, the final Random Forest model improved slightly after hyperparameter tuning and feature selection. Therefore, the final Random Forest Regressor is the best model for predicting PM2.5 concentration in this assignment.
"""